import "./globals.css";
import type { Metadata } from "next";
import Providers from "@/lib/Providers";
import Auth from "@/components/auth/Auth";


export const metadata: Metadata = {
  title: "Online School",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Providers>
      <Auth>
        <html lang="en">
          <body>{children}</body>
        </html>
      </Auth>
    </Providers>
  );
}
